[AppName]
one = "nps 客户端"
other = "nps 客户端"

[Install]
one = ""
other = "安装"

[Uninstall]
one = "uninstall"
other = "卸载"

[Success]
one = "successfully"
other = "成功"

[Fail]
one = "fail"
other = "失败"

[Start]
one = ""
other = "后台运行"

[Stop]
one = "stop"
other = "停止运行"

[Run]
one = "run"
other = "前台运行"