[AppName]
one = "nps client"
other = "nps client"

[Install]
one = "install"
other = "install"

[Uninstall]
one = "uninstall"
other = "uninstall"

[Success]
one = "successfully"
other = "successfully"

[Fail]
one = "fail"
other = "fail"

[Start]
one = ""
other = "fail"

[Stop]
one = "stop {{.AppName}}"

[Run]
one = "run {{.AppName}}"

[Version]
one = "show version of the {{.AppName}}"

[Lang]
one = "Set the language of the {{.AppName}}"